version: 2

jobs:
  macos:
    macos:
      xcode: "10.0"
    steps:
      - run: brew install vapor/tap/vapor
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: swift:5.0
    steps:
      - run:
          name: apt-get update
          command: apt-get update
      - run:
          name: apt-get install
          command: apt-get install -y libmysqlclient-dev libssl-dev
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: swift:5.0
    steps:
      - run:
          name: apt-get update
          command: apt-get update
      - run:
          name: apt-get install
          command: apt-get install -y libmysqlclient-dev libssl-dev
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - macos
      - linux
      - linux-release
